name: 'Build'

on:
  push:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  php-cs-fixer:
    name: 'Run PHP CS Fixer'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.2'
      - run: 'composer require --dev --no-install darkwebdesign/symfony-addon-transformers:7.3.x-dev'
      - uses: 'ramsey/composer-install@v3'
      - run: 'vendor/bin/php-cs-fixer fix --diff --dry-run --show-progress=none --ansi'

  phpstan:
    name: 'Run PHPStan'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.2'
      - run: 'composer require --dev --no-install darkwebdesign/symfony-addon-transformers:7.3.x-dev'
      - uses: 'ramsey/composer-install@v3'
      - run: 'vendor/bin/phpstan analyze --no-progress --ansi'

  rector:
    name: 'Run Rector'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.2'
      - run: 'composer require --dev --no-install darkwebdesign/symfony-addon-transformers:7.3.x-dev'
      - uses: 'ramsey/composer-install@v3'
      - run: 'vendor/bin/rector process --dry-run --no-progress-bar --ansi'

  composer-require-checker:
    name: 'Run Composer Require Checker'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.2'
      - uses: 'ramsey/composer-install@v3'
      - run: 'vendor/bin/composer-require-checker --ansi'

  composer-validate:
    name: 'Run Composer Validate'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.2'
      - run: 'composer validate'

  phpunit:
    name: 'Run PHPUnit'
    runs-on: 'ubuntu-24.04'
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
      fail-fast: false
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'shivammathur/setup-php@v2'
        with:
          php-version: "${{ matrix.php }}"
      - run: 'composer require --dev --no-install darkwebdesign/symfony-addon-transformers:7.3.x-dev'
      - uses: 'ramsey/composer-install@v3'
      - run: 'XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=phpunit-coverage.xml'
      - uses: 'qltysh/qlty-action/coverage@v2'
        with:
          token: "${{ secrets.QLTY_COVERAGE_TOKEN }}"
          files: 'phpunit-coverage.xml'
          format: 'clover'
